from flask import Flask, request, session, jsonify
import numpy as np
import pandas as pd
import requests
# import openai
import os
import json
import time
import joblib

from flask_cors import CORS

from google import genai

from transformJSONdata import fix_response


app = Flask(__name__)

# Set the secret key for the Flask application from an environment variable.
# NOTE: previously this was hardcoded and also overwritten by an unused
# `secret = os.urandom(24)` line above it. Sessions require a *stable*
# secret key across restarts, so keep it fixed (ideally read from an env var).
app.secret_key = b'\xd0\xd6\x7f\xdfI\xdd\x8c\xbd\xaf^>D,\x01\x9d\xdf~z\xd7\x0b+[\x06R'

# React will run on a different origin (e.g. http://localhost:3000) than
# Flask (e.g. http://localhost:5000), so CORS must be enabled and must allow
# credentials so the Flask session cookie is sent with each request.
CORS(app, supports_credentials=True, origins=["http://localhost:5173"])

# For session cookies to be sent cross-origin from React in the browser,
# these are typically required (adjust for your deployment / HTTPS setup):
app.config.update(
    SESSION_COOKIE_SAMESITE="None",
    SESSION_COOKIE_SECURE=True,  # requires HTTPS in production; use False for local http dev
)

client = genai.Client(api_key="AQ.Ab8RN6IWaSDko-JiHLyzn17BDE8uZpTAFkf9c0nNMdaWWp-XHg")

# Load the predictive model from a file
loaded_model = joblib.load('random_forest_model.pkl')
print("Model loaded successfully.")


# Define the column names for the model input
columns = ['no_of_dependents', 'education', 'self_employed', 'income_annum',
           'loan_amount', 'loan_term', 'cibil_score', 'residential_assets_value',
           'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value']


def get_response(prompt, model="gpt-3.5-turbo"):
    """
    Generates a chat response using OpenAI's GPT-3.5-turbo model based on the given prompt.

    This function creates a chat completion using the specified model. It sets the context of the chat
    as a loan acceptance prediction and assistant for small business enterprises and then generates a
    response to the user's prompt.

    Args:
    prompt (str): The prompt text from the user.
    model (str): The name of the GPT model to use. Defaults to "gpt-3.5-turbo".

    Returns:
    str: The chat response generated by the model.
    """
    messages = f"""
    "You are a nice loan acceptance prediction and assistant for small business enterprises"
    {prompt}
    """

    response = client.models.generate_content(
        model="gemini-3.5-flash-lite",
        contents=messages,
    )

    response = response.text

    cleaned_response = response.replace('```json', '').replace('```', '').strip()
    response_to_json = json.loads(cleaned_response)

    return json.dumps(response_to_json)


def get_predict_message(country):
    """
    Generates a custom message prompt for requesting information about loan sources for small business establishment.

    Args:
    country (str): The name of the country for which the user wants loan information.

    Returns:
    tuple: A tuple containing the generated prompt and the response from get_response function.
    """
    format = '''
    [
        {
            "myCountry": {
                "organizationName": "",
                "link": ""
            },
            "otherCountry": {
                "organizationName":"",
                "link": "",
                "Country": ""
            }
        },
        {
            "myCountry": {
                "organizationName": "",
                "link": ""
            },
            "otherCountry": {
                "organizationName":"",
                "link": "",
                "Country": ""
            }
        }
    ]
    '''

    prompt = "Hi, my country is {}. Kindly create a comprehensive list of places I can look out for to get a good loan for my small business establishment both in my country and other countries. Make sure you give the countries of the other countries! Give the answer strictly in this format: {}. Thanks.".format(country, format)

    prompt_response = get_response(prompt)

    return prompt, prompt_response


def get_further_response(prediction, question, prev_prompt, prev_response):
    """
    Generates a new prompt based on a previous conversation and a prediction result, then gets a response to it.

    Args:
    prediction (int): The prediction result (0 for 'Yes', 1 for 'No', others for neutral).
    question (str): The new question to be asked.
    prev_prompt (str): The previous prompt in the conversation.
    prev_response (str): The previous response in the conversation.

    Returns:
    tuple: A tuple containing the new prompt and the response from get_response function.
    """
    old = str(prev_prompt) + str(prev_response)
    previous_conv = ""
    rev_old = old[::-1]

    for char in rev_old:
        if len(previous_conv) < 2500:
            previous_conv += char

    final_previous_conv = previous_conv[::-1]

    if prediction == 0:  # Yes
        add_text = "again congrats on your approved loan"
    elif prediction == 1:  # No
        add_text = 'again sorry about the unapproved loan'
    else:
        add_text = ""

    final_previous_conv += add_text

    new_prompt = "Question: " + question + " | Previous Context: " + final_previous_conv + " | Instruction: Provide a concise, direct answer within 800 characters."

    further_response = get_response(new_prompt)

    return new_prompt, further_response


def get_business_idea(country, country_interest, capital_loan, amount, domain_interest, loan_pay_month):
    """
    Generates a prompt for business ideas based on user's financial situation and interests, and gets a response.

    Returns:
    tuple: A tuple containing the generated prompt and the response from get_response function.
    """
    format = '''
    [
        {
            "Business_Idea": "",
            "sector": "",
            "link": ""
        },
        {
            "Business Idea": "",
            "sector": "",
            "link": ""
        }
    ]
    '''

    if capital_loan == 'capital':
        prompt = "Hi, I'm from {}. Kindly help curate few nice business ideas, the domain sector of the business and like to learn more on the business, considering that I have a capital of {} US Dollars. My domain of business interest is {} and the country where I want to have my business is {}. Give the answer strictly in json format here is an example of what it should look like: {} Thanks.".format(country, amount, domain_interest, country_interest, format)
    elif capital_loan == 'loan':
        prompt = "Hi, I'm from {}. Kindly help curate few nice business ideas, the domain sector of the business and like to learn more on the business, considering that I got a loan of {} US Dollars and I am meant to pay back in {} months time. My domain of business interest is {} and the country where I want to have my business is {}. Give the answer strictly in json format here is an example of what it should look like: {} Thanks.".format(country, amount, loan_pay_month, domain_interest, country_interest, format)

    idea_response = get_response(prompt)

    return prompt, idea_response


def get_financial_advice(country, country_interest, description, capital_loan, amount, domain_interest, loan_pay_month):
    """
    Generates a prompt for obtaining financial advice based on the user's financial status and business interests, and gets a response.

    Returns:
    tuple: A tuple containing the generated prompt and the response from get_response function.
    """
    format = '''
    {
        "financial_breakdown": "",
        "link": ""
    }
    '''

    if capital_loan == 'capital':
        prompt = "Hi, I'm from {}. Kindly help curate a comprehensive financial breakdown with link to read more on it, for how I would manage my business considering that I have a capital of {} US Dollars. My domain of business interest is {}, the description is: {} and the country where I want to have my business is {}. Make your answer strictly in this format: {}.".format(country, amount, domain_interest, description, country_interest, format)
    elif capital_loan == 'loan':
        prompt = "Hi, I'm from {}. Kindly help curate a comprehensive financial breakdown with link to read more on it, for how I would manage my business considering that I got a loan of {} US Dollars and I am meant to pay back in {} months time. My domain of business interest is {}, the description is: {} and the country where I want to have my business is {}. Make your answer strictly in this format: {}.".format(country, amount, loan_pay_month, domain_interest, description, country_interest, format)

    advice_response = get_response(prompt)

    return prompt, advice_response


model = None

#JSON Serving


@app.route('/next_session', methods=["POST"])
def next_session():
    """
    API route to store the user's name and country in the session.

    Expects JSON body: { "name": "...", "country": "..." }

    Returns:
    jsonify: The stored name and country, confirming what was saved.
    """
    data = request.get_json(silent=True) or {}
    name = data.get('name', '').capitalize()
    country = data.get('country')

    if not name or not country:
        return jsonify({"error": "name and country are required"}), 400

    # NOTE: original code did `session = {}` here, which shadowed Flask's
    # session object with a plain dict and silently discarded it — nothing
    # was ever actually persisted. Writing into `session` directly fixes that.
    session["name"] = name
    session["country"] = country

    return jsonify({"name": name, "country": country})


@app.route('/chat_predict', methods=["POST"])
def chat_predict():
    """
    API route to handle loan predictions based on user input.

    Expects JSON body with the form fields previously submitted via HTML form:
    depend, education, employment, income, loan_amount, loan_term, score,
    resident, commercial, luxury, bank.

    Returns:
    jsonify: prediction, name, country, and bot_predict_response.
    """
    data = request.get_json(silent=True) or {}

    try:
        depend = data['depend']
        education = data['education']
        employment = data['employment']
        income = data['income']
        loan_amount = data['loan_amount']
        loan_term = data['loan_term']
        score = data['score']
        resident = data['resident']
        commercial = data['commercial']
        luxury = data['luxury']
        bank = data['bank']
    except KeyError as e:
        return jsonify({"error": f"missing field: {e.args[0]}"}), 400

    predict_columns = ['depend', 'education', 'employment', 'income', 'loan_amount', 'loan_term', 'score', 'resident', 'commercial', 'luxury', 'bank']
    arr = pd.DataFrame(
        np.array([[depend, education, employment, income, loan_amount, loan_term, score, resident, commercial, luxury, bank]]),
        columns=predict_columns
    )
    pred = int(loaded_model.predict(arr)[0])

    country = session.get("country", None)
    name = session.get("name", None)

    bot_predict_prompt, bot_predict_response = get_predict_message(country)
    bot_predict_response = json.loads(bot_predict_response)

    session["pred"] = pred
    session["bot_predict_response"] = bot_predict_response
    session["bot_predict_prompt"] = bot_predict_prompt

    return jsonify({
        "pred": pred,
        "name": name,
        "country": country,
        "bot_predict_response": bot_predict_response
    })


@app.route('/further_predict_chat', methods=["POST"])
def further_predict_chat():
    """
    API route to handle follow-up questions in the loan-prediction chat.

    Expects JSON body: { "question": "..." }

    Returns:
    jsonify: The follow-up response.
    """
    pred = session.get("pred", None)
    bot_predict_prompt = session.get("bot_predict_prompt", None)
    bot_predict_response = session.get("bot_predict_response", None)

    data = request.get_json(silent=True) or {}
    predict_question = data.get('question')
    if not predict_question:
        return jsonify({"error": "question is required"}), 400

    predict_prompt, predict_response = get_further_response(
        prediction=pred, question=predict_question,
        prev_prompt=bot_predict_prompt, prev_response=bot_predict_response
    )

    session["bot_predict_response"] = predict_response
    session["bot_predict_prompt"] = predict_question

    return jsonify({"response": predict_response})


@app.route('/business_idea', methods=["POST"])
def business_idea():
    """
    API route to handle business idea suggestions based on user inputs.

    Expects JSON body: country_interest, capital_loan, amount, domain_interest, loan_pay_month.

    Returns:
    jsonify: name, country, and bot_business_response.
    """
    data = request.get_json(silent=True) or {}

    try:
        country_interest = data['country_interest'].capitalize()
        capital_loan = data['capital_loan']
        amount = data['amount']
        domain_interest = data['domain_interest']
        loan_pay_month = data['loan_pay_month']
    except KeyError as e:
        return jsonify({"error": f"missing field: {e.args[0]}"}), 400

    country = session.get("country", None)
    name = session.get("name", None)

    bot_business_prompt, bot_business_response = get_business_idea(
        country=country,
        country_interest=country_interest,
        capital_loan=capital_loan,
        amount=amount,
        domain_interest=domain_interest,
        loan_pay_month=loan_pay_month
    )

    bot_business_response = json.loads(bot_business_response)

    session["bot_business_response"] = bot_business_response
    session["bot_business_prompt"] = bot_business_prompt

    return jsonify({
        "name": name,
        "country": country,
        "bot_business_response": bot_business_response
    })


@app.route('/further_business_chat', methods=["POST"])
def further_business_chat():
    """
    API route to handle follow-up questions in the business-idea chat.

    Expects JSON body: { "question": "..." }

    Returns:
    jsonify: The follow-up response.
    """
    bot_business_response = session.get("bot_business_response", None)
    bot_business_prompt = session.get("bot_business_prompt", None)

    data = request.get_json(silent=True) or {}
    business_question = data.get('question')
    if not business_question:
        return jsonify({"error": "question is required"}), 400

    business_prompt, business_response = get_further_response(
        prediction="", question=business_question,
        prev_prompt=bot_business_prompt, prev_response=bot_business_response
    )

    session["bot_business_response"] = business_response
    session["bot_business_prompt"] = business_question

    return jsonify({"response": business_response})


@app.route('/financial_advice', methods=["POST"])
def financial_advice():
    """
    API route to handle financial advice requests based on user inputs.

    Expects JSON body: country_interest, capital_loan, description, amount,
    domain_interest, loan_pay_month.

    Returns:
    jsonify: name, country, and bot_finance_response.
    """
    data = request.get_json(silent=True) or {}

    try:
        country_interest = data['country_interest'].capitalize()
        capital_loan = data['capital_loan']
        description = data['description']
        amount = data['amount']
        domain_interest = data['domain_interest']
        loan_pay_month = data['loan_pay_month']
    except KeyError as e:
        return jsonify({"error": f"missing field: {e.args[0]}"}), 400

    country = session.get("country", None)
    name = session.get("name", None)

    bot_finance_prompt, bot_finance_response = get_financial_advice(
        country=country,
        country_interest=country_interest,
        description=description,
        capital_loan=capital_loan,
        amount=amount,
        domain_interest=domain_interest,
        loan_pay_month=loan_pay_month
    )

    bot_finance_response = json.loads(bot_finance_response)

    session["bot_finance_response"] = bot_finance_response
    session["bot_finance_prompt"] = bot_finance_prompt

    return jsonify({
        "name": name,
        "country": country,
        "bot_finance_response": bot_finance_response
    })


@app.route('/further_finance_chat', methods=["POST"])
def further_finance_chat():
    """
    API route to handle follow-up questions in the financial-advice chat.

    Expects JSON body: { "question": "..." }

    Returns:
    jsonify: The follow-up response.
    """
    bot_finance_response = session.get("bot_finance_response", None)
    bot_finance_prompt = session.get("bot_finance_prompt", None)

    data = request.get_json(silent=True) or {}
    finance_question = data.get('question')
    if not finance_question:
        return jsonify({"error": "question is required"}), 400

    finance_prompt, finance_response = get_further_response(
        prediction="", question=finance_question,
        prev_prompt=bot_finance_prompt, prev_response=bot_finance_response
    )

    session["bot_finance_response"] = finance_response
    session["bot_finance_prompt"] = finance_question

    return jsonify({"response": finance_response})


if __name__ == '__main__':
    app.run(debug=True, use_reloader=False)